//! Traefik dynamic configuration file management.

use super::port_allocator::PortAllocation;
use anyhow::{Context, Result};
use std::path::PathBuf;

/// Manager for Traefik dynamic configuration files.
pub struct TraefikConfigManager {
    config_dir: PathBuf,
}

impl TraefikConfigManager {
    /// Create a new Traefik config manager.
    pub fn new(config_dir: &str) -> Self {
        Self {
            config_dir: PathBuf::from(config_dir),
        }
    }

    /// Generate the config file path for a VM.
    fn config_path(&self, slug: &str) -> PathBuf {
        self.config_dir.join(format!("vm-{}.yaml", slug))
    }

    /// Write Traefik configuration for a VM.
    pub fn write_vm_config(
        &self,
        slug: &str,
        subdomain: &str,
        internal_ip: &str,
        allocation: &PortAllocation,
        contract_id: &str,
    ) -> Result<()> {
        let config = self.generate_config(slug, subdomain, internal_ip, allocation, contract_id);

        // Ensure directory exists
        std::fs::create_dir_all(&self.config_dir).with_context(|| {
            format!("Failed to create Traefik config dir {:?}", self.config_dir)
        })?;

        let path = self.config_path(slug);
        std::fs::write(&path, config)
            .with_context(|| format!("Failed to write Traefik config to {:?}", path))?;

        tracing::debug!("Wrote Traefik config: {:?}", path);
        Ok(())
    }

    /// Delete Traefik configuration for a VM.
    pub fn delete_vm_config(&self, slug: &str) -> Result<()> {
        let path = self.config_path(slug);
        if path.exists() {
            std::fs::remove_file(&path)
                .with_context(|| format!("Failed to delete Traefik config {:?}", path))?;
            tracing::debug!("Deleted Traefik config: {:?}", path);
        }
        Ok(())
    }

    /// Generate Traefik YAML configuration for a VM.
    fn generate_config(
        &self,
        slug: &str,
        subdomain: &str,
        internal_ip: &str,
        allocation: &PortAllocation,
        contract_id: &str,
    ) -> String {
        let ssh_port = allocation.base;
        let timestamp = chrono::Utc::now().to_rfc3339();

        format!(
            r#"# Generated by dc-agent for VM {slug}
# Contract: {contract_id}
# Created: {timestamp}

http:
  routers:
    {slug}-http:
      rule: "Host(`{subdomain}`)"
      service: {slug}-http
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    {slug}-http:
      loadBalancer:
        servers:
          - url: "http://{internal_ip}:80"

tcp:
  routers:
    {slug}-ssh:
      rule: "HostSNI(`*`)"
      service: {slug}-ssh
      entryPoints:
        - tcp-{ssh_port}

  services:
    {slug}-ssh:
      loadBalancer:
        servers:
          - address: "{internal_ip}:22"
"#,
            slug = slug,
            subdomain = subdomain,
            internal_ip = internal_ip,
            contract_id = contract_id,
            timestamp = timestamp,
            ssh_port = ssh_port,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_generate_config() {
        let temp_dir = TempDir::new().unwrap();
        let manager = TraefikConfigManager::new(temp_dir.path().to_str().unwrap());

        let allocation = PortAllocation {
            base: 20000,
            count: 10,
            contract_id: "contract-123".to_string(),
        };

        let config = manager.generate_config(
            "k7m2p4",
            "k7m2p4.dc-lk.decent-cloud.org",
            "10.0.1.5",
            &allocation,
            "contract-123",
        );

        assert!(config.contains("Host(`k7m2p4.dc-lk.decent-cloud.org`)"));
        assert!(config.contains("http://10.0.1.5:80"));
        assert!(config.contains("tcp-20000"));
        assert!(config.contains("10.0.1.5:22"));
        assert!(config.contains("contract-123"));
    }

    #[test]
    fn test_write_and_delete_config() {
        let temp_dir = TempDir::new().unwrap();
        let manager = TraefikConfigManager::new(temp_dir.path().to_str().unwrap());

        let allocation = PortAllocation {
            base: 20000,
            count: 10,
            contract_id: "contract-123".to_string(),
        };

        manager
            .write_vm_config(
                "k7m2p4",
                "k7m2p4.dc-lk.decent-cloud.org",
                "10.0.1.5",
                &allocation,
                "contract-123",
            )
            .unwrap();

        let path = temp_dir.path().join("vm-k7m2p4.yaml");
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("k7m2p4"));

        manager.delete_vm_config("k7m2p4").unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn test_delete_nonexistent_config() {
        let temp_dir = TempDir::new().unwrap();
        let manager = TraefikConfigManager::new(temp_dir.path().to_str().unwrap());

        // Should not error when deleting non-existent file
        manager.delete_vm_config("nonexistent").unwrap();
    }
}
