[env]
RUST_BACKTRACE = "1"
CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE = "Makefile.toml"

[config]
default_to_workspace = false
end_task = "dfx-stop"
on_error_task = "dfx-stop"
unstable_features = ["CTRL_C_HANDLING"]

[tasks.default]
#dependencies = ["canister-tests", "format", "canister", "dfx-stop", "clippy", "clippy-canister", "build", "test"]
run_task = [
   { name="canister-tests" },
   { name="format" },
   { name="canister" },
   { name="dfx-stop" },
   { name="clippy" },
   { name="clippy-canister" },
   { name="build" },
   { name="test" }
]

[tasks.canister-tests]
command = "cargo"
args = ["test"]
cwd = "./ic-canister/"

[tasks.dfx-start]
script = ['''
#!/usr/bin/env bash
set -eEuo pipefail

cd ic-canister
for i in {1..10}; do dfx stop && break; sleep 1; dfx killall; sleep 1; pkill -9 -f versions || true; done;
dfx start --background --clean
while true; do
    dfx ping local && break;
    sleep 1;
done;
dfx canister create --all
''']

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.canister]
dependencies = ["dfx-start"]
command = "dfx"
args = ["build", "--all"]
cwd = "./ic-canister/"

[tasks.clippy]
command = "cargo"
args = ["clippy", "--tests"]

[tasks.clippy-canister]
command = "cargo"
args = ["clippy", "--tests", "--target=wasm32-unknown-unknown"]
cwd = "./ic-canister/"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
dependencies = ["build", "canister"]
command = "cargo"
args = ["test"]

[tasks.dfx-stop]
script = ['''
#!/usr/bin/env bash
set -eExuo pipefail

( cd ./ic-canister && for i in {1..10}; do dfx stop && break; sleep 1; pkill -9 -f versions || true; done; )
''']

