graph LR
  A[Public Internet] -- Forwarded Ports --> N[Node]
  A[Public Internet] -- HTTP/HTTPS Ingress --> Provider
  Provider -- SNI Routing --> RP[HAProxy/Nginx Reverse Proxy]
  RP -- Unterminated TLS traffic --> N
