graph TB
  D["Developer"] -->|Node Payment| TX
  TX["Transaction"] -->|Payment| Provider
  TX -->|Fee| FEE["Platform R&D"]

  FEE -->|Reputation Increase| RP["Provider Reputation"]
  FEE -->|Reputation Increase| RD["Dev Reputation"]

  RP --->|Multiple Uses| U1["Matching, Rewards, DAO Participation"]
  RD -->|Multiple Uses| U2["Matching, DAO Participation"]

  RP -->|Spend to decrease| RD
  RD -->|Spend to decrease| RP

  RP -->|Decay|Burn
  RD -->|Decay|Burn
