graph TB
  P["Decentralized Cloud Platform"]
  P --> S3a["Leveraging Reputation"]
  P --> S3b["Efficient Resource Allocation"]
  P --> S3c["Nodes with and without secure enclaves"]
  P --> S3d["Supports existing applications"]
  P --> S3e["DAO Governance"]
