genrule(
  name="whitepaper",
  out="whitepaper.pdf",
  srcs = glob(['*.tex']) + glob(['*.cls']) + glob(['*.bib']) + glob(['*.bbl']) + glob(['*.600pk']),
  cmd="""
  set -eEuo pipefail
  mkdir -p figures
  cp $(location //docs/whitepaper/figures:impl-reputation) $SRCDIR/figures/
  cp $(location //docs/whitepaper/figures:proposed_architecture) $SRCDIR/figures/
  cp $(location //docs/whitepaper/figures:proposed-solution) $SRCDIR/figures/
  cp $(location //docs/whitepaper/figures:impl-networking) $SRCDIR/figures/
  latexmk -pdf whitepaper &&
  mv whitepaper.pdf $OUT
  """,
)
