name = "decent-cloud-import-worker"
main = "src/import-index.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "production"
CANISTER_ID = "ggi4a-wyaaa-aaaai-actqq-cai"

# Local development configuration
[env.local]
name = "decent-cloud-import-worker-local"
vars = { ENVIRONMENT = "local", CANISTER_ID = "uxrrr-q7777-77774-qaaaq-cai" }