name = "decent-cloud-api"
main = "src/index.ts"
compatibility_date = "2025-10-30"
compatibility_flags = ["global_fetch_strictly_public", "nodejs_compat"]

[observability]
enabled = true

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "decent-cloud-db"
database_id = "4efecfb3-c6a5-42fb-a3b5-83eea3e215dc"
migrations_dir = "migrations"

[[d1_databases]]
binding = "TEST_DB"
database_name = "decent-cloud-test"
database_id = "a74f720b-1402-4e54-bc54-3a5472a147ae"
migrations_dir = "migrations"

# Environment variables
[vars]
ENVIRONMENT = "production"
CANISTER_ID = "ggi4a-wyaaa-aaaai-actqq-cai"
FLUSH_INTERVAL_SECONDS = "5"
MAX_RETRY_ATTEMPTS = "3"

# Production routes
[[routes]]
pattern = "decent-cloud.kalaj.org"
zone_name = "kalaj.org"

# Development configuration
[env.development]
name = "decent-cloud-api-dev"
vars = { ENVIRONMENT = "development" }

# Local development configuration
[env.local]
name = "decent-cloud-api-local"

[env.local.vars]
ENVIRONMENT = "local"
CANISTER_ID = "ggi4a-wyaaa-aaaai-actqq-cai"
FLUSH_INTERVAL_SECONDS = "5"
MAX_RETRY_ATTEMPTS = "3"
TEST_DB_NAME = "decent-cloud-test"

[[env.local.d1_databases]]
binding = "DB"
database_name = "decent-cloud-db"
database_id = "4efecfb3-c6a5-42fb-a3b5-83eea3e215dc"
migrations_dir = "migrations"

[[env.local.d1_databases]]
binding = "TEST_DB"
database_name = "decent-cloud-test"
database_id = "a74f720b-1402-4e54-bc54-3a5472a147ae"
migrations_dir = "migrations"