DEPS_THIRD_PARTY = [
    "//third-party:anyhow",
    "//third-party:ed25519-compact",
    "//third-party:data-encoding",
    "//third-party:strum",
    "//third-party:strum_macros",
]

rust_library(
    name = "dcc-common",
    srcs = [
        "src/lib.rs",
    ],
    deps = DEPS_THIRD_PARTY,
    edition = "2021",
    visibility = ["PUBLIC"],
)
