// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Image } from "./Image";
import type { Location } from "./Location";
import type { ServerType } from "./ServerType";

export type BackendCatalog = { serverTypes: Array<ServerType>, locations: Array<Location>, images: Array<Image>, };
