// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Image = { id: string, name: string, osType: string, osVersion: string | null, };
