// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerType = { id: string, name: string, cores: number, memoryGb: number, diskGb: number, priceMonthly: number | null, priceHourly: number | null, };
