// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerMetrics = { cpuPercent: number | null, memoryPercent: number | null, diskPercent: number | null, networkInBytes: bigint | null, networkOutBytes: bigint | null, };
