// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerStatus } from "./ServerStatus";

export type Server = { id: string, name: string, status: ServerStatus, publicIp: string | null, serverType: string, location: string, image: string, createdAt: string, };
