//! CSV format constants for consistent serialization/deserialization

/// Standard CSV headers for server offerings in the correct order
pub const CSV_HEADERS: &[&str] = &[
    "offer_name",
    "Description", 
    "Unique Internal identifier",
    "Product page URL",
    "Currency",
    "Monthly price",
    "Setup fee",
    "Visibility",
    "Product Type",
    "Virtualization type", 
    "Billing interval",
    "Stock",
    "Processor Brand",
    "Processor Amount",
    "Processor Cores",
    "Processor Speed",
    "Processor Name",
    "Memory Error Correction",
    "Memory Type",
    "Memory Amount",
    "Hard Disk Drive Amount",
    "Total Hard Disk Drive Capacity",
    "Solid State Disk Amount",
    "Total Solid State Disk Capacity",
    "Unmetered",
    "Uplink speed",
    "Traffic",
    "Datacenter Country", 
    "Datacenter City",
    "Datacenter Coordinates",
    "Features",
    "Operating Systems",
    "Control Panel",
    "GPU Name",
    "Payment Methods",
];